2019-08-08 21:23:30,578 ERROR: Exception on /reset_password [GET] [in c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Zac\PythonFlask\app\routes.py", line 259, in reset_password_request
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
2019-08-08 21:24:10,864 ERROR: Exception on /reset_password [GET] [in c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Zac\PythonFlask\app\routes.py", line 259, in reset_password_request
    if current_user.is_authenticated:
TypeError: 'bool' object is not callable
2019-08-08 21:24:25,193 INFO: Blog app starting up [in C:\Users\User\Zac\PythonFlask\app\__init__.py:43]
2019-08-08 21:24:28,179 ERROR: Exception on /reset_password [GET] [in c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Zac\PythonFlask\app\routes.py", line 272, in reset_password_request
    title='reset Password', form=form)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Zac\PythonFlask\app\templates\reset_password_request.html", line 18, in template
    <p>{{ form.submit() }}</p>
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\users\user\zac\pythonflask\env\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
